defaults:
  -
    scope:
      path: "jekyllBase"
      type: "pages"
    values:
      layout: "default"
      author: "Nobody"
      category: "site"
baseurl: ""
permalink: none
title: Jekyll Base Default Title
kramdown:
  input: GFM